spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/causw
    username: causwlocaluser
    password: causwlocalpw

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
  jwt:
    secret: jwtsecretkey

  config:
    import: classpath:gcs-config.yaml, classpath:email-config.yaml, classpath:password-config.yaml

  deploy:
    prod: false